In [7]:
#                                                                     ques-1

In [8]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
type(array_list)

numpy.ndarray

In [9]:
type(list_)

list

In [ ]:
""" So ,yes there is difference between the data type of both the variables.
    the (list_) variable has a data type of list and the (array_list) variable has a datatype of ndarray means n dimension array 
    which is one dimension at this point."""

In [10]:
#                                                                      ques-2

In [27]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [25]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
#                                                                        ques-3    

In [28]:
array_list = np.array(object = list_, dtype = int)
""" Yes, there will be difference in datatype of array_list but not in list_ variable because we are changing the 
    datatype of array_list from string to integer but not in list_ variable so the datatype of list_ variable will 
    remain same as string."""

In [29]:
array_list

array([1, 2, 3, 4, 5])

In [31]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [32]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [ ]:
#                                                                       ques-4

In [33]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array.shape

(2, 3)

In [34]:
num_array.size

6

In [35]:
#                                                                       ques-5

In [40]:
new_array = np.zeros((3,3))
new_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#                                                                       ques-6

In [50]:
diag_matrix = np.diag([1,1,1,1,1,])
diag_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])